fix: remove url dependency in the browser
dignifiedquire/borc pull request #38
Opened 2018-12-13 17:26 UTC by hugomrdias

This PR reduces bundle size (OKR work).

26.86KB > 22.63KB -15.74%

Basically removes url dep in the browser bundle. 

Needs
 - [x] https://github.com/ipfs/aegir/pull/307

2018-12-13 17:53 UTC, dignifiedquire commented on package.json
> +    "name": "borc",
can you please leave the indent as it was?

2018-12-13 17:53 UTC, dignifiedquire commented on .travis.yml
> -  - node_js: 8
why is node 8 not supported anymore?

2018-12-13 18:01 UTC, hugomrdias commented
should be fixed now

2018-12-20 11:58 UTC, hugomrdias commented
this PR is ready to merge

2018-12-20 12:44 UTC, vmx reviewed
Looks good to me, but I'd like to get an approval from @dignifiedquire.

2018-12-23 17:47 UTC, dignifiedquire requested changes
- actual content changes lgtm
- please drop the unrelated changes (package-lock & white space diff) 
- nitpick: this is not really a `fix`, but rather a `feat`, or `refactor`

2018-12-23 17:47 UTC, dignifiedquire commented on package-lock.json
> +{
can we please not add this? if this is important, please put it into its own PR with a description why.

2018-12-23 17:47 UTC, dignifiedquire commented on benchmarks/index.js
> +  const enc = new fastCbor.Encoder({ stream (chunk) {
please remove all the white space changes, unless they have to be there to make linting pass

2018-12-23 17:47 UTC, dignifiedquire commented on .travis.yml
> +  - node_js: 8
superfluous whitespace

2018-12-24 11:36 UTC, hugomrdias commented
fixed all feedback and squashed
white space is needed because aegir uses a new config

2018-12-24 12:19 UTC, dignifiedquire approved these changes
thanks

2018-12-24 12:20 UTC, merged

2018-12-26 14:28 UTC, hugomrdias commented
can you release pls ? so this starts bubbling up